# Generated by Django 3.2.9 on 2022-04-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='pp.jpg', null=True, upload_to=''),
        ),
    ]
